apiVersion: v1
kind: Service
metadata:
  name: fiap-games-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: fiap-games-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-games-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-games-api
  template:
    metadata:
      labels:
        app: fiap-games-api
    spec:
      containers:
      - name: fiap-games-api
        image: acrfiaplucas.azurecr.io/fiap-games-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__RabbitMq
          value: "amqp://guest:guest@rabbitmq-service:5672"